# Generated by Django 4.2.30 on 2026-05-15 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_two_factor_fields'),
        ('accounts', '0003_user_apple_sub_user_facebook_id_user_google_sub'),
        ('accounts', '0004_create_default_admin'),
    ]

    operations = [
    ]
