# Generated by Django 4.2.30 on 2026-05-15 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_create_default_admin'),
    ]

    operations = [
    ]
