# Generated by Django 6.0.4 on 2026-04-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skills', models.TextField()),
                ('experience', models.IntegerField()),
                ('price_per_hour', models.FloatField()),
                ('availability', models.BooleanField(default=True)),
                ('rating', models.FloatField(default=0)),
                ('jobs_completed', models.IntegerField(default=0)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
            ],
        ),
    ]
