# Generated by Django 4.2.30 on 2026-05-19 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='messaging_m_booking_2e8334_idx',
            old_name='messaging_message_booking_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='messaging_m_sender__5ce791_idx',
            old_name='messaging_message_sender_receiver_idx',
        ),
    ]
